apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sgs-ace-is
spec:
  source:
    git:
      uri: https://github.com/Mattar555/dha-yalta-ace-sgs-flow
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'sgs-ace-is:v1'
  strategy:
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key
      dockerfilePath: .
