apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops-ace
  namespace: dev
spec:
  usersAnonymousEnabled: true
  server:
    route:
      enabled: true
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, system:cluster-admins, role:admin
