apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: yalta-dha-trigger-binding
      template:
        name: yalta-dha-trigger-template
