apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: app-name
    description: The name of the application
    default: "app-connect-enterprise-gitops"
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
      kind: Task
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: deploy
    taskRef:
      name: deploy
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - git-clone
  - name: commit-yamls
    taskRef:
      kind: Task
      name: commit-yamls
    params:
      - name: app-name
        value: "$(params.app-name)"
      - name: sha
        value: "$(tasks.git-clone.results.commit)"
    workspaces:
      - name: source
        workspace: shared-workspace
    runAfter:
    - deploy
